### ISSUE TITLE
Doesn't work in iOS 4

### ISSUE THREAD

**Issue by mwaterfall** [0xced/iOS-Artwork-Extractor#1]
Title says it all :)

No artwork is shown in the list when running on the simulator in iOS 4.

**Comment by 0xced** [comment]
I've been able to get a few images, but only those actually used by the app. This requires some more investigation to extract everything.

**Comment by 0xced** [comment]
Support for iOS 4
Closed by e39de93201d0c76061286f7937d072fc990dd0d6

**Comment by mwaterfall** [comment]
Nice ;)
