### ISSUE TITLE
How about iOS 6?

### ISSUE THREAD

**Issue by lexrus** [0xced/iOS-Artwork-Extractor#10]
Hi, there.
Thank you for this repo. I learned a lot from the artwork images.
The iOS 6 beta is online today. Is this project compatible with iOS 6? I'm downloading Xcode 4.5.

**Comment by ekdevdes** [comment]
+1

**Comment by 0xced** [comment]
Full support for iOS 6 was finalized in 95f2376f1764cad35aa4b8845544ae3d3231615b.
