### ISSUE TITLE
HIG Compatibility

### ISSUE THREAD

**Issue by ekdevdes** [0xced/iOS-Artwork-Extractor#11]
This is a cool project but does the HIG even allow devs to use apple's images in their apps?

**Comment by ghost** [comment]
i found my way here looking for the answer to the same question.

**Comment by odrobnik** [comment]
The answer is: Yes. The HIG only prohibits use of icons for a different purpose than the users expect. i.e. I once had an app rejected because I used the edit button icon for settings.
