### ISSUE TITLE
Mountain Lion unable to create output folder

### ISSUE THREAD

**Issue by odrobnik** [0xced/iOS-Artwork-Extractor#13]
Under 10.8.1 the app is unable to create an output folder on desktop.

**Comment by 0xced** [comment]
I just tried with Xcode 4.4.1 (4F1003) / iPhone Simulator 5.1 on Mountain Lion 10.8.1 Build 12B19 and I experienced no problem at all. Is there a log in your console that could give us more information about the problem you are experiencing?

**Comment by 0xced** [comment]
I just added a log if the directory creation fails in ad714db0e871af53749bb93b637eec02810c2481

**Comment by odrobnik** [comment]
Even though I am not aware of any change now I see the folder being created. Probably my mistake. Closing Issue.
