### ISSUE TITLE
Map directions icon not extracted?

### ISSUE THREAD

**Issue by winzig** [0xced/iOS-Artwork-Extractor#15]
I don't seem to find the car icon used in iOS 6 maps that the user pushes to get driving directions. It's a white car on a two-tone green button with a white border. Any idea why?

**Comment by ZevEisenberg** [comment]
Maybe it’s vector?

**Comment by 0xced** [comment]
If it’s inside the Maps app, you should be able to extract it from a iOS firmware, see [Extracting more artwork](../wiki/Extracting-more-artwork) for instructions.
