### ISSUE TITLE
IPA Not Displayed for iOS 7

### ISSUE THREAD

**Issue by DenVog** [0xced/iOS-Artwork-Extractor#20]
After updating to iOS 7, I no longer see an IPA tab on devices or in the simulator.

**Comment by leviathan** [comment]
Confirmed. Don't see the IPA tap in iOS 7

```
 2014-01-07 09:22:49.516 iOS Artwork Extractor[17276:60b] 'Mobile Applications' directory not found.
```

**Comment by 0xced** [comment]
By default, _iOS Artwork Extractor_ searches for IPAs in `~/Music/iTunes/Mobile Applications` and `~/Music/iTunes/iTunes Media/Mobile Applications`. If your iTunes library is not there, just set the `MOBILE_APPLICATIONS_DIRECTORY` environment variable to the full path of your `Mobile Applications` directory.
