### ISSUE TITLE
OS5 compatibility

### ISSUE THREAD

**Issue by neilkachu** [0xced/iOS-Artwork-Extractor#5]
Will crash on OS5:

line 93: ArtworkViewController.m

Detected an attempt to call a symbol in system libraries that is not present on the iPhone:
open$UNIX2003 called from function APEFindSymbol in image UIKit Artwork Extractor.

**Comment by 0xced** [comment]
Please upgrade to the latest version, this issue is already fixed.

**Comment by neilkachu** [comment]
Doh, Cheers!

**Comment by Instrumentry** [comment]
I'm getting "Could not find mapped image..." errors when I run it in iOS 5.0 Simulator. Xcode 4.2.1 and SDK 5.0.
Using the latest version of the extractor.
