### ISSUE TITLE
ipod/music tab bar icons

### ISSUE THREAD

**Issue by dannybabiy** [0xced/iOS-Artwork-Extractor#6]
Is there anyway to grab the ipod/music tab bar icons?  I don't see them being detected even on the device.

**Comment by dannybabiy** [comment]
To elaborate, I mean the images that are contained in the MPMediaPickerController from the MediaPlayer framework

**Comment by 0xced** [comment]
They are inside **iPodUI.framework**. You can grab them on the device or by mounting the decrypted firmware dmg matching the simulator version.

**Comment by dannybabiy** [comment]
I looked on iphone4 and there are only 8 images for iPodUI, none of which are tab bar icons.

**Comment by 0xced** [comment]
What is your iOS version? And are you running on your **device** or on the **simulator**? I get 64 images with all the toolbar items when running on an iPhone 4 **device** on iOS 5.0.1.

**Comment by dannybabiy** [comment]
Oh, thats strage, I was running on 5.0.1 device, but after deleting the app from device and compiling again I get the 64.  Thanks!
