### ISSUE TITLE
Missing Mail archive icon

### ISSUE THREAD

**Issue by ghost** [0xced/iOS-Artwork-Extractor#8]
Title says it all. I can't find the icon that sometimes replaces the trash can in the Mail app. Have I missed it, or is it genuinely not displayed or exported by this app? It's the only icon I need :)

**Comment by 0xced** [comment]
It is possible to extract artwork from Apple apps by mounting a decrypted iOS firmware before running the extractor. I will soon add a wiki entry to explain how you mount a decrypted iOS firmware.

**Comment by 0xced** [comment]
You can find instructions to [mount a decrypted iOS firmware](https://github.com/0xced/UIKit-Artwork-Extractor/wiki/Extracting-more-artwork) on the wiki.
