### ISSUE TITLE
Glossy buttons aren't working in iOS 5.1 Simulator

### ISSUE THREAD

**Issue by pnc** [0xced/iOS-Artwork-Extractor#9]
On the iOS 5.1 Simulator, the glossy button is simply not drawn.

I can (and will) take a look at why, but I want to make sure you aren't already trying to fix it.

Thanks!

**Comment by 0xced** [comment]
The `UIGlassButton` class was simply removed in iOS 5.1. If you want the glossy button feature, you have to download the iOS 5.0 simulator.

I will remove the glossy button tab when `UIGlassButton` is not available.

**Comment by pnc** [comment]
Understood. Might pop that information in the README.

Thanks for a sweet tool!
